---
name: headless-shell

networks:
  headless-shell:
    name: headless-shell

services:
  headless-shell:
    container_name: headless-shell
    image: docker.io/chromedp/headless-shell
    restart: unless-stopped
    ports:
      - 9222:9222
      - 9223:9223
    networks:
      - headless-shell
