---
name: otel-jaeger

networks:
  backend:
    name: otel-jaeger

services:
  otel-collector:
    container_name: otel-collector
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/cmd/otelcontribcol/Dockerfile
    image: otel/opentelemetry-collector-contrib:latest
    networks:
      - backend
    volumes:
      - ./otelcol.config.yaml:/etc/otelcol/config.yml
    command: --config /etc/otelcol/config.yml
    depends_on:
      - jaeger
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    networks:
      - backend
    ports:
      - 16686:16686 # Jaeger UI
